package com.onboardguard.shared.config;

/**
 * Centralized configuration key constants for SystemConfig database entries.
 *
 * This class ensures strong type safety and prevents typos when accessing
 * configuration values from SystemConfigService.
 *
 * All keys here MUST match exactly with:
 * - Column `config_key` in database table `system_config`
 * - Entries seeded in `data.sql`
 *
 * Organization by category (corresponding to ConfigCategoryType enum):
 * - SCREENING: Risk scoring, thresholds, multipliers, bonuses
 * - STORAGE: Cloud storage, presigned URLs, expiry times
 * - BUSINESS: SLAs, auto-reject rules, business logic
 * - SYSTEM: General application configuration
 *
 * @since 1.0.0
 */
public final class ConfigConstants {

    private ConfigConstants() {
        // Private constructor prevents instantiation
    }

    // SCREENING CONFIGURATION KEYS
    // Category: SCREENING
    /**
     * Jaro-Winkler similarity threshold for fuzzy name matching.
     * Type: DOUBLE (0.0 to 1.0, default 0.80)
     * Usage: AdvancedScreeningStrategy, BasicScreeningStrategy
     */
    public static final String SCREENING_THRESHOLD_FUZZY = "SCREENING_THRESHOLD_FUZZY";

    /**
     * Risk score threshold to classify a candidate as MEDIUM risk.
     * Type: DOUBLE (default 31.0)
     * Usage: RiskScoringEngine.classify()
     */
    public static final String SCREENING_THRESHOLD_MEDIUM = "SCREENING_THRESHOLD_MEDIUM";

    /**
     * Risk score threshold to classify a candidate as HIGH risk.
     * Type: DOUBLE (default 61.0)
     * Usage: RiskScoringEngine.classify()
     */
    public static final String SCREENING_THRESHOLD_HIGH = "SCREENING_THRESHOLD_HIGH";

    // SCREENING MULTIPLIERS (Corroboration)
    // Category: SCREENING
    /**
     * Corroboration multiplier when only candidate name matches watchlist.
     * Type: DOUBLE (default 0.5)
     * Usage: RiskScoringEngine.corroborationMultiplier()
     */
    public static final String SCREENING_MULT_NAME_ONLY = "SCREENING_MULT_NAME_ONLY";

    /**
     * Corroboration multiplier when name and one ID match (PAN or Aadhaar).
     * Type: DOUBLE (default 0.8)
     * Usage: RiskScoringEngine.corroborationMultiplier()
     */
    public static final String SCREENING_MULT_NAME_ONE_ID = "SCREENING_MULT_NAME_ONE_ID";

    /**
     * Corroboration multiplier when name and two IDs match (PAN + Aadhaar).
     * Type: DOUBLE (default 1.0)
     * Usage: RiskScoringEngine.corroborationMultiplier()
     */
    public static final String SCREENING_MULT_NAME_TWO_IDS = "SCREENING_MULT_NAME_TWO_IDS";

    /**
     * Corroboration multiplier when name and organization match.
     * Type: DOUBLE (default 0.75)
     * Usage: RiskScoringEngine.corroborationMultiplier()
     */
    public static final String SCREENING_MULT_NAME_ORG = "SCREENING_MULT_NAME_ORG";

    /**
     * Corroboration multiplier when name, organization, and designation all match.
     * Type: DOUBLE (default 1.0)
     * Usage: RiskScoringEngine.corroborationMultiplier()
     */
    public static final String SCREENING_MULT_NAME_ORG_DESIGNATION = "SCREENING_MULT_NAME_ORG_DESIGNATION";

    // SCREENING BONUSES
    // Category: SCREENING
    /**
     * Risk score bonus when a match is in CRIMINAL watchlist category.
     * Type: DOUBLE (default 15.0)
     * Usage: RiskScoringEngine.categoryBonus()
     */
    public static final String SCREENING_BONUS_CRIMINAL = "SCREENING_BONUS_CRIMINAL";

    /**
     * Risk score bonus when a match is in PEP (Politically Exposed Person) category.
     * Type: DOUBLE (default 15.0)
     * Usage: RiskScoringEngine.categoryBonus()
     */
    public static final String SCREENING_BONUS_PEP = "SCREENING_BONUS_PEP";

    /**
     * Risk score bonus when a watchlist entry has HIGH severity level.
     * Type: DOUBLE (default 10.0)
     * Usage: RiskScoringEngine.categoryBonus()
     */
    public static final String SCREENING_BONUS_SEVERITY_HIGH = "SCREENING_BONUS_SEVERITY_HIGH";

    // FEATURE TOGGLES & STRATEGY
    // Category: SCREENING
    /**
     * Active screening strategy engine to use.
     * Type: STRING (valid values: "BASIC" or "ADVANCED")
     * Default: "ADVANCED"
     * Usage: ScreeningOrchestrationService.resolveActiveStrategy()
     */
    public static final String ACTIVE_SCREENING_STRATEGY = "ACTIVE_SCREENING_STRATEGY";

    /**
     * Feature toggle: Whether to automatically reject candidates with HIGH risk score.
     * Type: BOOLEAN (default false)
     * Usage: Screening workflow decision logic
     */
    public static final String SCREENING_AUTO_REJECT_ENABLED = "SCREENING_AUTO_REJECT_ENABLED";

    // STORAGE CONFIGURATION
    // Category: STORAGE
    /**
     * TTL (Time To Live) in minutes for presigned URLs generated by CloudStorageService.
     * Type: INTEGER (default 15 minutes)
     * Usage: CloudStorageService.generatePresignedUrl()
     */
    public static final String STORAGE_PRESIGNED_URL_TTL_MINUTES = "STORAGE_PRESIGNED_URL_TTL_MINUTES";

    // AUTHENTICATION & SECURITY
    // Category: SYSTEM
    /**
     * JWT token expiration time in milliseconds.
     * Type: INTEGER (default 900000 = 15 minutes)
     * Usage: AuthServiceImpl, JwtTokenProvider
     */
    public static final String AUTH_JWT_EXPIRATION_MS = "AUTH_JWT_EXPIRATION_MS";

    // BUSINESS RULES & SLA
    // Category: BUSINESS
    /**
     * SLA (Service Level Agreement) in minutes for officers to review a flagged screening.
     * Type: INTEGER (default 30)
     * Usage: Officer notification, SLA breach detection
     */
    public static final String SLA_MINUTES = "SLA_MINUTES";

    // DEFAULT VALUES
    // Used by SystemConfigService when database key is not found.
    public static final class Defaults {
        private Defaults() {}

        // Screening
        public static final double FUZZY_THRESHOLD = 0.80;
        public static final double MEDIUM_THRESHOLD = 31.0;
        public static final double HIGH_THRESHOLD = 61.0;

        // Multipliers
        public static final double MULT_NAME_ONLY = 0.5;
        public static final double MULT_NAME_ONE_ID = 0.8;
        public static final double MULT_NAME_TWO_IDS = 1.0;
        public static final double MULT_NAME_ORG = 0.75;
        public static final double MULT_NAME_ORG_DESIGNATION = 1.0;

        // Bonuses
        public static final double BONUS_CRIMINAL = 15.0;
        public static final double BONUS_PEP = 15.0;
        public static final double BONUS_SEVERITY_HIGH = 10.0;

        // Strategy & Features
        public static final String ACTIVE_STRATEGY = "ADVANCED";
        public static final boolean AUTO_REJECT_ENABLED = false;

        // Storage
        public static final int PRESIGNED_URL_TTL_MINUTES = 15;

        // Auth
        public static final int JWT_EXPIRATION_MS = 900000; // 15 minutes

        // Business
        public static final int SLA_MINUTES = 30;
    }
}

